name: Build Windows EXE

on:
  push:
    branches: ['**']          # <— build every branch
    tags: ['v*']              # still build on version tags
  pull_request:
    branches: ['**']          # PRs from any branch
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build (optional)'
        required: false
        default: ''

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout (triggering branch by default)
        uses: actions/checkout@v4
        with:
          # If manually dispatched with a ref input, use it. Otherwise use the event ref (current branch).
          ref: ${{ github.event.inputs.ref != '' && github.event.inputs.ref || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile Qt resources (if .qrc present)
        shell: pwsh
        run: |
          if (Test-Path .\resources.qrc) {
            pyrcc5 .\resources.qrc -o .\resources_rc.py
          }

      - name: PyInstaller build
        shell: pwsh
        run: |
          $Main = "SashCartCompiler.py"
          $Name = "SashCartCompiler"
          pyinstaller `
            --noconfirm `
            --windowed `
            --onefile `
            --name $Name `
            --hidden-import PyQt5.sip `
            --hidden-import PyQt5.QtCore `
            --hidden-import PyQt5.QtGui `
            --hidden-import PyQt5.QtWidgets `
            --add-data "images;images" `
            $Main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SashCartCompiler-win-${{ github.ref_name }}-${{ github.sha }}
          path: dist/SashCartCompiler.exe

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SashCartCompiler-win-${{ github.ref_name }}-${{ github.sha }}
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          fil
