name: Build Windows EXE

permissions:
  contents: write  # needed for releases

on:
  push:
    branches: ['**']          # build every branch
    tags: ['v*']              # build on version tags (v1.2.3)
  pull_request:
    branches: ['**']
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build (optional)'
        required: false
        default: ''

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout (triggering ref by default)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref != '' && github.event.inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller pyinstaller-hooks-contrib

      - name: Compile Qt resources (if .qrc present)
        shell: pwsh
        run: |
          if (Test-Path .\resources.qrc) {
            python -m PyQt5.pyrcc_main .\resources.qrc -o .\resources_rc.py
          }

      - name: PyInstaller build
        shell: pwsh
        run: |
          $Main = "SashCartCompiler.py"
          $Name = "SashCartCompiler"
          pyinstaller --noconfirm --windowed --onefile `
            --name $Name `
            --hidden-import PyQt5.sip `
            --hidden-import PyQt5.QtCore `
            --hidden-import PyQt5.QtGui `
            --hidden-import PyQt5.QtWidgets `
            --add-data "images;images" `
            $Main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SashCartCompiler-win-${{ github.ref_name }}-${{ github.sha }}
          path: dist/SashCartCompiler.exe

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SashCartCompiler-win-${{ github.ref_name }}-${{ github.sha }}
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SashCartCompiler.exe
